background {
    monitor = 
    path = /home/user/Images/default.png
    # color = rgba(0,0,0,1)
    blur_passes = 1
    blur_size = 1
    contrast = 1
    brightness = 1
}

input-field {
    monitor = 
    size = 200, 50
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.35
    dots_center = true
    dots_rounding = -1
    placeholder_text =
    fade_on_empty = false
    fail_text = Oh... Try again!
    outer_color = rgba(0, 0, 0, 0)
    inner_color = rgba(0, 0, 0, 0.2)
    font_color = rgba(220, 215, 186, 0.8)
    font_family = JetBrains Mono
    check_color = rgb(204, 136, 34)
    position = 0, 0
    haling = center
    valing = center
}
